package modelo;

public enum Especialidad {
    PEDIATRA,
    MEDICO_GENERAL,
    CARDIOLOGO,
    DERMATOLOGO,
    TRAUMATOLOGO,
    GINECOLOGO,
    NEUROLOGO,
    OTORRINOLARINGOLOGO,
    OFTALMOLOGO,
    PSIQUIATRA
}
